name: "artifactory maven publish"
description: "Uploads artifact to maven"

inputs:
  host:
    description: 'Artifactory hostname'
    required: true
  username:
    description: 'Artifactory username'
    required: true
  password:
    description: 'Artifactory password'
    required: true
  group:
    description: 'Artifact group'
    required: true
  name:
    description: 'Artifact name'
    required: true
  version:
    description: 'Artifact version'
    required: true
  buildDir:
    description: 'Directory to make artifact from'
    required: false
  distributionsDir:
    description: 'Directory containing distribution zip files'
    required: false
    default: './build/distributions'
  tycho:
    description: 'Tycho file path'
    required: true
    default: './tycho.yaml'
  provisioning:
    description: 'Provisioning directory path'
    required: true
    default: './provisioning'
  includeDotFiles:
    description: 'Include dot files in build zip'
    required: false
    default: 'false'
  release-tag-prefix:
    description: 'Prefix for release tag detection'
    required: false
    default: 'v'

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: refresh-cw
  color: blue