name: "artifactory publish npm package"
description: "Uploads artifact to npm registry"

outputs:
  url:
    description: "artifact url"

inputs:
  host:
    description: 'Artifactory hostname'
    required: true
  email:
    description: 'Artifactory email'
    required: false
  username:
    description: 'Artifactory username'
    required: false
  password:
    description: 'Artifactory password'
    required: true
  name:
    description: 'Artifact name'
    required: true
  version:
    description: 'Artifact version'
    required: true

runs:
  using: 'node12'
  main: 'dist/index.js'

branding:
  icon: refresh-cw
  color: blue
